print("Введите цифры a, b и f: ")
a = int(input("a = "))
b = int(input("b = "))
f = int(input("f = "))
x = (a + b - f / a) + f * a * a - (a + b)
print("Вычисляем по формуле: x = (а + b — f / а) + f * a * a — (a + b)")
print("x = ", x)
